M48
; DRILL file KiCad 10.0.1 date 2026-04-27T10:03:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-27T10:03:17-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X135.255Y-72.39
X135.255Y-135.89
X192.405Y-72.39
X192.405Y-135.89
M30
